Multi <- read.csv(file.choose())
View(Multi)
is.na(Multi)
attach(Multi)
summary(Multi)
hist(R.D.Spend)
hist(Administration)
hist(Marketing.Spend)
hist(Profit)
barplot(R.D.Spend)
barplot(Administration)
barplot(Marketing.Spend)
barplot(Profit)
boxplot(R.D.Spend)
boxplot(Administration)
boxplot(Marketing.Spend)
boxplot(Profit)
pairs(Multi)
levels(Multi$State)
lm_Profit <- lm(Profit~R.D.Spend+Administration+State+Marketing.Spend, data = Multi)
summary(lm_Profit)
str(Multi)
install.packages("corpcor")
library(corpcor)
cor2pcor(cor(Multi1))
lm_ProfitR <- lm(Profit~R.D.Spend)
summary(lm_ProfitR)
lm_ProfitA <- lm(Profit~Administration)
summary(lm_ProfitA)
lm_ProfitM <- lm(Profit~Marketing.Spend)
summary(lm_ProfitM)
lm_ProfitS <- lm(Profit~State)
summary(lm_ProfitS)
lm_ProfitRM <- lm(Profit~R.D.Spend+Marketing.Spend)
summary(lm_ProfitRM)
influence.measures(lm_Profit)
install.packages("mvinfluence")
library(mvinfluence)
influenceIndexPlot(lm_Profit,id.n=3)
lm_Profit1<- lm(Profit~R.D.Spend+Administration+Marketing.Spend+State, data = Multi[-50,])
summary(lm_Profit1)
View(Multi)
vif(lm_Profit1)
avPlots(lm_Profit1)
lm_Profit2<- lm(Profit~R.D.Spend+Marketing.Spend+State, data = Multi[-50,])
summary(lm_Profit2)
lm_Profit3<- lm(Profit~R.D.Spend+Marketing.Spend, data = Multi[-50,])
summary(lm_Profit3)
plot(lm_Profit3)
hist(lm_Profit3)


