Computer <- read.csv(file.choose())
Comp <- Computer[,-1]
View(Comp)
str(Comp)
is.na(Comp)
attach(Comp)
summary(Comp)
hist(price)
hist(speed)
hist(hd)
hist(ram)
hist(screen)
hist(ads)
hist(trend)
barplot(price)
barplot(speed)
barplot(hd)
barplot(ram)
barplot(screen)
barplot(ads)
barplot(trend)
boxplot(price)
boxplot(speed)
boxplot(hd)
boxplot(ram)
boxplot(screen)
boxplot(ads)
boxplot(trend)
plot(speed,price)
plot(hd,price)
plot(ram,price)
plot(screen,price)
plot(cd,price)
plot(multi,price)
plot(premium,price)
plot(ads,price)
plot(trend,price)
lm_comp <- lm(price~speed+hd+ram+screen+cd+multi+premium+ads+trend)
summary(lm_comp)
influence.measures(lm_Profit)
library(mvinfluence)
influenceIndexPlot(lm_comp)
lm_comp1 <- lm(price~speed+hd+ram+screen+cd+multi+premium+ads+trend,data = Comp[-c(1441,1701),])
summary(lm_comp1)
vif(lm_comp1)
library(mvinfluence)
avPlots(lm_comp1)
lm_comp2 <- lm(price~speed+hd+ram+screen+premium+ads+trend,data = Comp[-c(1441,1701),])
summary(lm_comp2)
avPlots(lm_comp2)
plot(lm_comp)
hist(lm_comp)
plot(lm_comp)
plot(lm_comp2)